POST http://localhost:8080/events 
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InpleW5hYkBnb29nbGUuY29tIiwiZXhwIjoxNzQzNDU4NDE4LCJ1c2VySWQiOjN9.bI5JDQOywZY3VaBJJBIAM-1aXNJZ0P-ugXkOkkx9_yI

{
    "name": "apply celebration",
    "description": "celebration",
    "location": "ECE UT School",
    "dateTime": "2025-01-01T15:30:00.000Z"
}