PUT http://localhost:8080/events/3
Content-Type: application/json

{
    "name": "celebration",
    "description": "celebrating our happiness",
    "location": "planet Earth",
    "dateTime": "2025-01-01T15:30:00.000Z"
}